// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models
{
    public partial class Producto
    {
        public Producto()
        {
            Venta = new HashSet<Venta>();
        }

        public int Id { get; set; }
        public string Descripcion { get; set; }
        public decimal? SubTotal { get; set; }
        public decimal? PrecioUnitario { get; set; }

        public virtual ICollection<Venta> Venta { get; set; }
    }
}