// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models
{
    public partial class Venta
    {
        public int Id { get; set; }
        public DateTime? FechaVenta { get; set; }
        public decimal MontoTotal { get; set; }
        public int IdProducto { get; set; }
        public int IdUsuario { get; set; }

        public virtual Producto IdProductoNavigation { get; set; }
        public virtual Usuario IdUsuarioNavigation { get; set; }
    }
}